"""The last N months as a series, so the app can answer "am I improving?".

A two-month comparison says whether this month beat last month, which is as
much noise as signal — one holiday, one late invoice. A run of months is what
shows a direction.

The gap question is the design decision here. A month with nothing recorded is
not a month where nothing was spent, and drawing it as zero asserts something
the data does not support. Dropping it instead is worse: the line then runs
August straight into October as if they were adjacent. So every month in the
range is returned, in order, and the empty ones are flagged — the reader sees
a gap as a gap.
"""

from __future__ import annotations

from typing import Dict, List

import store

#: Months shown by default. Twelve is a year of context; on a phone the labels
#: stop being legible much beyond that.
DEFAULT_SPAN = 6


def series(months: Dict[str, object], current: str, span: int = DEFAULT_SPAN) -> List[Dict]:
    """``span`` months ending at ``current``, oldest first.

    Contiguous by construction: the keys are generated by walking back from
    ``current`` rather than taken from what happens to be stored, so a month
    with no data still occupies its place on the axis.
    """
    span = max(1, min(int(span), 24))
    keys = [store.shift_month(current, offset) for offset in range(-(span - 1), 1)]

    result = []
    for key in keys:
        budget = months.get(key)
        result.append(_point(key, budget))
    return result


def _point(key: str, budget) -> Dict:
    if budget is None or (not budget.incomes and not budget.expenses):
        # `empty` rather than a zero row: nothing was recorded, which is not
        # the same claim as nothing was spent.
        return {"month": key, "income": 0.0, "expenses": 0.0, "net": 0.0, "empty": True}
    return {
        "month": key,
        "income": round(budget.total_income(), 2),
        "expenses": round(budget.total_expenses(), 2),
        "net": round(budget.net(), 2),
        "empty": False,
    }


def averages(points: List[Dict]) -> Dict:
    """Means over the months that actually hold data.

    Empty months are excluded rather than counted as zero, which would drag
    every average toward nothing and make a sparse history look thrifty.
    """
    filled = [p for p in points if not p["empty"]]
    if not filled:
        return {"months": 0, "income": 0.0, "expenses": 0.0, "net": 0.0}
    return {
        "months": len(filled),
        "income": round(sum(p["income"] for p in filled) / len(filled), 2),
        "expenses": round(sum(p["expenses"] for p in filled) / len(filled), 2),
        "net": round(sum(p["net"] for p in filled) / len(filled), 2),
    }
